version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTICSEARCH_VERSION
    container_name: elasticsearch
    restart: always
    environment:
      # - bootstrap.memory_lock=true
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=$ELASTICSEARCH_SECURITY_ENABLED
      - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD # address of elasticsearch docker container which kibana will connect
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    # volumes:
    #   -   /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: ["stack"]
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:$ELASTICSEARCH_VERSION
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
  #     - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD # address of elasticsearch docker container which kibana will connect
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   networks: ["stack"]
networks:
  stack: {}
